services:
  street-light-server:
    container_name: street-lights-server
    image: streetlightsserver:latest
    ports:
      - 3000:3000
    depends_on:
      - redis
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
